#!/usr/bin/env bash
# Transfer a file to server
if [ $# -ne 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	# Disable host checking on a one time basis use
	scp -o StrictHostKeyChecking=no UserKnownHostsFile=/dev/null -i "$4" "$1" "$3@$2":
fi
