#!/usr/bin/env bash
# Installs nginx web server

sudo apt update -y
sudo apt upgrade -y
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx restart
