#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get install nginx -y
# Allow nginx access through firewall
# ufw allow 'Nginx HTTP'
# Edit default ubuntu html page
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
