#!/usr/bin/env bash
# Install nginx web server

apt-get update
apt-get -y install nginx

# Allow nginx access through firewall
ufw allow 'Nginx HTTP'

# Overwrite default html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html

service nginx start

# 301 redirection
rdrct='server_name _;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;'
sed -i "s|server_name\s*_;|$rdrct|" /etc/nginx/sites-available/default

# Write custom 404 error page
echo "Ceci n'est pas une page
" > /usr/share/nginx/html/custom_404.html

# Enable custom 404
err_pg="listen [::]:80 default_server;\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sed -i "s|listen \[::\]:80 default_server;|$err_pg|" /etc/nginx/sites-available/default

# Enable default conf
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
