#!/usr/bin/env bash
# Installs nginx web server
# Configure it to listen on port 80
# Adds redirection, custom 404 page, & header

sudo apt update -y
sudo apt upgrade -y
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen \[::\]:80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i '/listen \[::\]:80 default_server;/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sed -i '/error_page 404 \/custom_404.html;/a location = /custom_404.html {root /usr/share/nginx/html; internal;}' /etc/nginx/sites-available/default
sed -i "/listen \[::\]:80 default_server;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
sudo service nginx restart
