#!/usr/bin/env bash
# Install & configure HAproxy

apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get update
apt-get -y install haproxy=2.8.\*

echo "
frontend lb
	bind *:80
	mode http
	default_backend web-servers

backend web-servers
	mode http
	balance roundrobin
	server web-01 204.236.223.200:80 check
	server web-02 100.25.201.56:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy restart
