#!/usr/bin/env bash
# Makes nginx run as nginx user
pkill apache2
chmod 755 /etc/nginx/nginx.conf
sed -i 's/\b80\b/&80/' /etc/nginx/sites-available/default
sudo -u nginx bash -c "service nginx restart"
